name = "tanshuku-url"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "URL_CACHE"
id = "203784620acc4309979ffab0caa69a04"
preview_id = "640fc4572c2b4859a248fcfa3ff542ef"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2c3f947c282248a9b53aa4b7279ed16a"
preview_id = "24e439fffcdf474682c8aeff57defe24"

[[d1_databases]]
binding = "DB"
database_name = "tanshuku-db"
database_id = "299dd393-cb6e-4efd-ab72-00a1d34e58c6"

[[routes]]
pattern = "t.0g0.xyz"
custom_domain = true

[vars]
SHORT_DOMAIN = "https://t.0g0.xyz"
OIDC_ISSUER = "https://id.0g0.xyz"

# Secretsはwrangler secret putで設定:
# GOOGLE_SAFE_BROWSING_API_KEY
# OIDC_CLIENT_ID
# OIDC_CLIENT_SECRET
